### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by FredyC** [lipp/doclets#131]
I am not sure what's wrong. In the list I see badge that says failed, but I cannot seem to find any details anywhere about failure.

https://doclets.io/BlackDice/b3-chief/master

The doclets.yml look like this

```yaml
dir: src

packageJson: package.json

articles:

  - Overview: README.md

branches:

  - master
```
